export const INIT_DATA = "INIT_DATA"
export const INIT_DATA_SUCCESS = "INIT_DATA_SUCCESS"

export const INIT_ANKE_TOKEN = "INIT_ANKE_TOKEN"
export const INIT_ANKE_TOKEN_SUCCESS = "INIT_ANKE_TOKEN_SUCCESS"

export const ALL_TASKS = 'ALL_TASKS'
export const ALL_TASKS_SUCCESS = 'ALL_TASKS_SUCCESS'

export const ALL_FEEDBACK_TYPES = "ALL_FEEDBACK_TYPES"
export const ALL_FEEDBACK_TYPES_SUCCESS = "ALL_FEEDBACK_TYPES_SUCCESS"

export const ALL_ENGINEERS = "ALL_ENGINEERS"
export const ALL_ENGINEERS_SUCCESS = "ALL_ENGINEERS_SUCCESS"

export const ALL_DEVICES = "ALL_DEVICES"
export const ALL_DEVICES_SUCCESS = "ALL_DEVICES_SUCCESS"

export const ALL_FIX_TYPES = "ALL_FIX_TYPES"
export const ALL_FIX_TYPES_SUCCESS = "ALL_FIX_TYPES_SUCCESS"

export const ALL_OPEN_TASKS = 'ALL_OPEN_TASKS'
export const ALL_OPEN_TASKS_SUCCESS = 'ALL_OPEN_TASKS_SUCCESS'

export const ALL_ALLOCATED_TASKS = 'ALL_ALLOCATED_TASKS'
export const ALL_ALLOCATED_TASKS_SUCCESS = 'ALL_ALLOCATED_TASKS_SUCCESS'

export const ALL_PROCESSED_TASKS = 'ALL_PROCESSED_TASKS'
export const ALL_PROCESSED_TASKS_SUCCESS = 'ALL_PROCESSED_TASKS_SUCCESS'

export const ALL_CLOSED_TASKS = 'ALL_CLOSED_TASKS'
export const ALL_CLOSED_TASKS_SUCCESS = 'ALL_CLOSED_TASKS_SUCCESS'

export const ALL_DELIVERING_PRODUCTS = 'ALL_DELIVERING_PRODUCTS'
export const ALL_DELIVERING_PRODUCTS_SUCCESS = 'ALL_DELIVERING_PRODUCTS_SUCCESS'
export const ALL_INSTALL_PRODUCTS = 'ALL_INSTALL_PRODUCTS'
export const ALL_INSTALL_PRODUCTS_SUCCESS = 'ALL_INSTALL_PRODUCTS_SUCCESS'
export const ALL_TRAIN_PRODUCTS = 'ALL_TRAIN_PRODUCTS'
export const ALL_TRAIN_PRODUCTS_SUCCESS = 'ALL_TRAIN_PRODUCTS_SUCCESS'


export const ALL_MY_MENUS = 'ALL_MY_MENUS'
export const ALL_MY_MENUS_SUCCESS = 'ALL_MY_MENUS_SUCCESS'


export const SOME_PRODUCTS = 'SOME_PRODUCTS'
export const SOME_PRODUCTS_SUCCESS = 'SOME_PRODUCTS_SUCCESS'

export const NEW_DELIVER_RECORD = 'NEW_DELIVER_RECORD'
export const NEW_DELIVER_RECORD_SUCCESS = 'NEW_DELIVER_RECORD_SUCCESS'
export const NEW_INSTALL_RECORD = 'NEW_INSTALL_RECORD'
export const NEW_INSTALL_RECORD_SUCCESS = 'NEW_INSTALL_RECORD_SUCCESS'
export const NEW_TRAIN_RECORD = 'NEW_TRAIN_RECORD'
export const NEW_TRAIN_RECORD_SUCCESS = 'NEW_TRAIN_RECORD_SUCCESS'

export const NEW_CLIENT = 'NEW_CLIENT'
export const NEW_CLIENT_SUCCESS = 'NEW_CLIENT_SUCCESS'
export const REMOVE_CLIENT = 'REMOVE_CLIENT'
export const REMOVE_CLIENT_SUCCESS = 'REMOVE_CLIENT_SUCCESS'

export const DELIVER_RECORD_BY_PRODUCT = "DELIVER_RECORD_BY_PRODUCT"
export const DELIVER_RECORD_BY_PRODUCT_SUCCESS = "DELIVER_RECORD_BY_PRODUCT_SUCCESS"
export const INSTALL_RECORD_BY_PRODUCT = "INSTALL_RECORD_BY_PRODUCT"
export const INSTALL_RECORD_BY_PRODUCT_SUCCESS = "INSTALL_RECORD_BY_PRODUCT_SUCCESS"
export const TRAIN_RECORD_BY_PRODUCT = "TRAIN_RECORD_BY_PRODUCT"
export const TRAIN_RECORD_BY_PRODUCT_SUCCESS = "TRAIN_RECORD_BY_PRODUCT_SUCCESS"


export const ALL_FIXES_BY_ID = "ALL_FIXES_BY_ID" //获取反馈记录id对象的所有维修记录
export const ALL_FIXES_BY_ID_SUCCESS = "ALL_FIXES_BY_ID_SUCCESS"

export const TASK_BY_ID = 'TASK_BY_ID'
export const TASK_BY_ID_SUCCESS = 'TASK_BY_ID_SUCCESS'

export const NEW_TASK = 'NEW_TASK'
export const NEW_TASK_SUCCESS = 'NEW_TASK_SUCCESS'

export const UNPROCESS_TASK = 'UNPROCESS_TASK'
export const UNPROCESS_TASK_SUCCESS = 'UNPROCESS_TASK_SUCCESS'

export const CLOSE_TASK = "CLOSE_TASK"
export const CLOSE_TASK_SUCCESS = "CLOSE_TASK_SUCCESS"

export const OPEN_TASK = "OPEN_TASK"
export const OPEN_TASK_SUCCESS = "OPEN_TASK_SUCCESS"

export const NEW_FIX = 'NEW_FIX'
export const NEW_FIX_SUCCESS = 'NEW_FIX_SUCCESS'

export const UPDATE_TASK = 'UPDATE_TASK'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'

export const REMOVE_TASK = 'REMOVE_TASK'
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS'

export const UPDATE_SELECTED = 'UPDATE_SELECTED'

export const BIND_ANKE = "BIND_ANKE"
export const BIND_ANKE_SUCCESS = "BIND_ANKE_SUCCESS"
export const UNBIND_ANKE = "UNBIND_ANKE"
export const UNBIND_ANKE_SUCCESS = "UNBIND_ANKE_SUCCESS"
export const LOGIN_ANKE = "LOGIN_ANKE"
export const LOGIN_ANKE_SUCCESS = "LOGIN_ANKE_SUCCESS"


export const WX_PARAMS = 'WX_PARAMS'
export const WX_PARAMS_SUCCESS = 'WX_PARAMS_SUCCESS'

export const WX_CHECK_TOKEN = 'WX_CHECK_TOKEN'
export const WX_CHECK_TOKEN_SUCCESS = 'WX_CHECK_TOKEN_SUCCESS'

export const WX_OPENID_URL = "WX_OPENID_URL"
export const WX_OPENID_URL_SUCCESS = "WX_OPENID_URL_SUCCESS"

export const WX_OPENID = "WX_OPENID"
// export const WX_OPENID_SUCCESS = "WX_OPENID_SUCCESS"

// 消息
export const MSG_BY_USER = "MSG_BY_USER"
export const MSG_BY_USER_SUCCESS = "MSG_BY_USER_SUCCESS"
export const MSG_DELETE = "MSG_DELETE"
export const MSG_DELETE_SUCCESS = "MSG_DELETE_SUCCESS"
export const MSG_READ = "MSG_READ"
export const MSG_READ_SUCCESS = "MSG_READ_SUCCESS"

// 记录
export const DELIVER_RECORDS_BY_USER = "DELIVER_RECORDS_BY_USER"
export const DELIVER_RECORDS_BY_USER_SUCCESS = "DELIVER_RECORDS_BY_USER_SUCCESS"
export const INSTALL_RECORDS_BY_USER = "INSTALL_RECORDS_BY_USER"
export const INSTALL_RECORDS_BY_USER_SUCCESS = "INSTALL_RECORDS_BY_USER_SUCCESS"
export const TRAIN_RECORDS_BY_USER = "TRAIN_RECORDS_BY_USER"
export const TRAIN_RECORDS_BY_USER_SUCCESS = "TRAIN_RECORDS_BY_USER_SUCCESS"
export const CLIENT_RECORDS = "CLIENT_RECORDS"
export const CLIENT_RECORDS_SUCCESS= "CLIENT_RECORDS_SUCCESS"
export const VALID_SALES_RECORDS = "VALID_SALES_RECORDS"
export const VALID_SALES_RECORDS_SUCCESS = "VALID_SALES_RECORDS_SUCCESS"

export const UPDATE_REGISTER_CODE_DEADLINE = "UPDATE_REGISTER_CODE_DEADLINE"
export const UPDATE_REGISTER_CODE_DEADLINE_SUCCESS = "UPDATE_REGISTER_CODE_DEADLINE_SUCCESS"

export const OSS_UPLOAD_FILE = "OSS_UPLOAD_FILE"
export const OSS_UPLOAD_FILE_SUCCESS = "OSS_UPLOAD_FILE_SUCCESS"

export const OSS_DELETE_FILE = "OSS_DELETE_FILE"
export const OSS_DELETE_FILE_SUCCESS = "OSS_DELETE_FILE_SUCCESS"

export const NEW_OSS_CLIENT = 'NEW_OSS_CLIENT'
export const OSS_TOKEN = 'OSS_TOKEN'
export const OSS_TOKEN_SUCCESS = 'OSS_TOKEN_SUCCESS'

export const SAVE_RECORD = "SAVE_RECORD" //用于触发保存操作
export const SAVE_RECORD_PROCESS = "SAVE_RECORD_PROCESS"
export const SAVE_RECORD_PROCESS_RESET = "SAVE_RECORD_PROCESS_RESET"
export const TASK = "TASK"
export const RECORD_ID = "RECORD_ID"
export const IMG_TYPE = "IMG_TYPE"
export const PRODUCT_NAME = "PRODUCT_NAME"
export const CURRENT_TASK = "CURRENT_TASK"
export const CURRENT_FIX = "CURRENT_FIX"
export const CURRENT_PRODUCT = "CURRENT_PRODUCT"
export const CURRENT_MSG = "CURRENT_MSG"
export const UPDATE_CLOSE_WINDOW = "UPDATE_CLOSE_WINDOW"
export const CURRENT_AREA = "CURRENT_AREA"

// export const ADD_TO_CART = 'ADD_TO_CART'
// export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
//
// export const ALL_MANUFACTURERS = 'ALL_MANUFACTURER'
// export const ALL_MANUFACTURERS_SUCCESS = 'ALL_MANUFACTURER_SUCCESS'
